# More examples of Codefresh YAML can be found at
# https://codefresh.io/docs/docs/yaml-examples/examples/

version: "1.0"
# Stages can help you organize your steps in stages
stages:
  - "clone"
  - "build"
  - "test"

steps:   
  clone:
    title: "Cloning repository"
    type: "git-clone"
    repo: "nihal-dev/docker-image-codefresh"
    # CF_BRANCH value is auto set when pipeline is triggered
    # Learn more at codefresh.io/docs/docs/codefresh-yaml/variables/
    revision: "${{CF_BRANCH}}"
    git: "nihal-dev"
    stage: "clone"

  build:
    title: "Building Docker image"
    type: "build"
    image_name: "nihals/codefresh-nginx"
    working_directory: "${{clone}}" ##name of the stage were you cloned the repostory
    tag: "${{CF_SHORT_REVISION}}"
    dockerfile: "Dockerfile"
    stage: "build"

